name: Lint
on: push
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install --silent
      - name: yarn lint
        run: yarn lint
      - name: yarn format
        run: yarn format
